version: '3.4'
services:
    bot:
      build: .
      ports:
        - "8000:8000"
      environment:
        TOKEN: ${TOKEN:-"token"}
        POSTGRES_USER: postgres
        POSTGRES_DBNAME: bot_test
        POSTGRES_HOST: bot.postgres
        POSTGRES_PORT: 5432
      command: python /app/main.py --loglevel=DEBUG
      container_name: bot.app
      tty: true
      networks:
        - bot
      volumes:
        - .:/app/
    postgresql:
      build:
        context: ./postgres/
      container_name: bot.postgres
      ports:
        - "5436:5432"
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_DB: bot_test
      volumes:
      - postgres-data:/var/lib/postgresql/data/
      networks:
      - bot

volumes:
  postgres-data:

networks:
  bot:
